apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/repositories.yaml
  - argocd/applications/jovies.yaml
  - argocd/applications/portfolio.yaml
  - ingress/ingress.yaml

